name: loyalty
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.5
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.8.1
  hive_generator: ^0.7.0+2

dependency_overrides:
  dartx: ^0.3.0
  
flutter:
  uses-material-design: true